nelmio_api_doc:
    models: { use_jms: true }
    documentation:
        info:
            title: Bilemo
            description: Une API avec un portefeuille d'utilisateurs pour chaque client ainsi que des produits.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Connexion à l'API
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                            default: info@mail.com
                                        password:
                                            type: string
                                            default: password
                                    type: object
                    responses:
                        '200':
                            description: OK
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: []
                    
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
